Url refactor.
mikitachab/pimicroclimate pull request #4
Opened 2019-06-02 19:18 UTC by WlodekLipski

Index page, table and plot pages added. Small pages refactor done.
Need to connect value from dropdown list with data on table page and
plot.

2019-06-02 19:40 UTC, mikitachab requested changes

2019-06-02 19:40 UTC, mikitachab commented on measurements/urls.py
> +    path('data/', views.table)
why not just:
```python
path('table/', views.table)
```

2019-06-02 19:40 UTC, mikitachab commented on measurements/views.py
> +def view(request):
please consider more descriptive name

2019-06-02 19:40 UTC, mikitachab commented on prepare_venv.sh
> +python3 -m venv virtualenv
I don't understand why you did that. `venv` and `virtualenv` a different packages. they are doing mostly the same, `venv` is prebuilt but `virtualenv` more preferable to use and `venv` is more preferable name for virtual environment. if you had trouble with running that scripts please try:
```bash
pip install virtualenv
```
and please change it as it was before.

2019-06-03 04:54 UTC, WlodekLipski commented
Commit changes.

2019-06-03 07:40 UTC, mikitachab approved these changes

2019-06-03 07:40 UTC, merged